export const playOutcomes = {
  '1-1': { type: 'touchdown', yards: 0, description: 'Touchdown Pass' },
  '1-2': { type: 'turnover', yards: 70, description: 'Interception – 30 yards downfield' },
  '1-3': { type: 'run', yards: 20, description: 'Reverse Play – +20 yards' },
  '1-4': { type: 'sack', yards: -15, description: 'Quarterback Sack – -15 yards' },
  '1-5': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '1-6': { type: 'penalty', yards: 5, description: 'Offside Defense – +5 yards' },
  '2-1': { type: 'pass', yards: 45, description: 'Trick Play – +45 yards' },
  '2-2': { type: 'turnover', yards: null, description: 'FUMBLE – Turnover' },
  '2-3': { type: 'turnover', yards: 60, description: 'Interception – 40 yards downfield' },
  '2-4': { type: 'run', yards: -10, description: 'Tackle in Backfield – -10 yards' },
  '2-5': { type: 'penalty', yards: 15, description: 'Pass Interference – +15 yards' },
  '2-6': { type: 'run', yards: 5, description: 'HB Run – +5 yards' },
  '3-1': { type: 'touchdown', yards: 0, description: 'Touchdown Run' },
  '3-2': { type: 'turnover', yards: 40, description: 'Fumble – Opposite 40 yard line' },
  '3-3': { type: 'penalty', yards: -10, description: 'Holding – -10 yards' },
  '3-4': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '3-5': { type: 'penalty', yards: 5, description: 'Offside Defense – +5 yards' },
  '3-6': { type: 'touchdown', yards: 0, description: 'Touchdown Pass' },
  '4-1': { type: 'sack', yards: -15, description: 'Quarterback Sack – -15 yards' },
  '4-2': { type: 'penalty', yards: -10, description: 'Holding – -10 yards' },
  '4-3': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '4-4': { type: 'touchdown', yards: 0, description: 'Touchdown Run' },
  '4-5': { type: 'run', yards: 10, description: 'HB Run – +10 yards' },
  '4-6': { type: 'penalty', yards: 5, description: 'Offside Defense – +5 yards' },
  '5-1': { type: 'run', yards: 20, description: 'Reverse Play – +20 yards' },
  '5-2': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '5-3': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '5-4': { type: 'penalty', yards: 15, description: 'Pass Interference – +15 yards' },
  '5-5': { type: 'run', yards: 5, description: 'QB Draw – +5 yards' },
  '5-6': { type: 'pass', yards: 40, description: 'Trick Play – +40 yards' },
  '6-1': { type: 'turnover', yards: 90, description: 'Interception – 10 yards downfield' },
  '6-2': { type: 'turnover', yards: 10, description: 'Fumble – Opposite 10 yard line' },
  '6-3': { type: 'run', yards: 5, description: 'HB Run – +5 yards' },
  '6-4': { type: 'incomplete', yards: 0, description: 'Incomplete Pass' },
  '6-5': { type: 'penalty', yards: 15, description: 'Pass Interference – +15 yards' },
  '6-6': { type: 'touchdown', yards: 0, description: 'Touchdown Run' },
}